import Head from "next/head"
import Header from "@/components/Header"
import AddTodo from "@/components/AddTodo"

export default function Home() {
  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#FFFEF2] h-[100vh] px-8">
        <Header />
        <AddTodo />
      </main>
    </>
  )
}
